### ISSUE TITLE
rescan terminated when quit wallet after importing private key

### ISSUE THREAD

**Issue by lixujasonFengXing** [ZcashFoundation/zecwallet#119]
Rescan terminated when quit wallet after importing private key, when relaunch wallet, rescan would not resume so that sometimes balance of the newly imported address would not be shown correctly. Users need to rescan manually in order to show balance correctly, which cause bad user experience.

**Comment by adityapk00** [comment]
Thank you for filing this issue. You are right, in that if the user quite the wallet while rescan is in progress, it doesn't update the balances. 

The problem is that zcashd doesn't currently have a good way to detect if a rescan is in progress, so the wallet doesn't know what's going on.

I'll try to add some workarounds and a "troubleshooting" option in the menu.

**Comment by lixujasonFengXing** [comment]
Users should be reminded with a progress bar or at least a message "rescan taking progress" in the left corner, so that they would not get confused & restart the wallet after importing private key, which lead to the above issue. Also, there should be an button to perform rescanning when the balance is shown wrong, rather than doing that with cmd in terminal.

**Comment by adityapk00** [comment]
Added the rescan button.
