### ISSUE TITLE
Weird start menu link

### ISSUE THREAD

**Issue by Morilli** [ZcashFoundation/zecwallet#125]
Starting from release 0.6.6, the start menu shortcut, when right-clicked, does no longer show an option to uninstall. Furthermore, it is generally not possible to navigate to the "real" zecwallet.exe using the shortcut in the startmenu; trying to follow the link doesn't actually lead anywhere.

I am currently using Windows 10 Pro x64, Build 1903.

**Comment by adityapk00** [comment]
Thanks for reporting this. Let me look into it. Are you using ZecWallet 0.6.6? 

This might have something to do with renaming the executable from zec-qt-wallet.exe -> zecwallet.exe

**Comment by Morilli** [comment]
I am currently using version 0.6.8, but I think when I tested it the issue did not occur on version 0.6.5, but it did on 0.6.6.

**Comment by adityapk00** [comment]
So unfortunately this is a side effect of renaming the app, and caused by the upgrade from 0.6.5 (which is before the rename).

I can't find a way to easily fix it in the underlying installer framework, and the workaround seems to be to uninstall ZecWallet (from the Add/Remove Programs) and install the latest version. 

I will mark this bug as closed, but please let me know if you see any more weird issues.

**Comment by Morilli** [comment]
Hm, that seems to resolve that issue. Although I wonder, if the app was renamed, is there a reason for the default installation location to still be ``C:\Program Files (x86)\zec-qt-wallet`` instead of ``...\zec-wallet``?

**Comment by Morilli** [comment]
I just wanna mention that this issue has fully returned with release 0.6.10.

**Comment by adityapk00** [comment]
Damn it!

I assume it came back when you upgraded to 0.6.10. 

Let me look into it!
