### ISSUE TITLE
--headless mode still requires a connection to an X server

### ISSUE THREAD

**Issue by alchemydc** [ZcashFoundation/zecwallet#127]
`zcash@zcashd:~/dl/zecwallet-v0.6.8$ ./zecwallet --headless
qt.qpa.screen: QXcbConnection: Could not connect to display localhost:10.0
Could not connect to any X display.`

Expected behaviour is that --headless invocation should not require a connection to an X11 server.

**Comment by adityapk00** [comment]
Yeah, unfortunately the headless mode is not really headless yet. The problem I ran into was that in order to fix another issue (People having old/incorrect versions of Qt), I had to statically link Qt into the binary, which creates a dependency on the X server. 

I need to refactor the headless mode.

**Comment by adityapk00** [comment]
Headless mode is not supported by Zecwallet. Please use github.com/adityapk00/zecwallet-light-cli
