### ISSUE TITLE
Sign the installer MSI

### ISSUE THREAD

**Issue by PRabahy** [ZcashFoundation/zecwallet#130]
Is it possible to sign the installer MSI? Right now Windows says that it is from an Unknown Publisher. This is still appearing even though https://github.com/ZcashFoundation/zecwallet/issues/106 is closed.

**Comment by adityapk00** [comment]
Signing the windows installer requires buying a license (It's $500!), and since this is an open source project, I can't really afford it. See the discussion here: https://news.ycombinator.com/item?id=19329330

ZecWallet provides pgp signed installers, so you can verify they came from the right source. Please see our FAQ on how to verify: https://docs.zecwallet.co/installation/#verifying-signatures

**Comment by PRabahy** [comment]
Any chance this is something that the ZcashFoundation would pay for? I know how to use pgp, but many people that I recommend Zcash to don't.
