### ISSUE TITLE
Error: Couldn't start the embedded zcashd

### ISSUE THREAD

**Issue by TheRealMrCoffie** [ZcashFoundation/zecwallet#166]
I installed ZecWallet on a rather fresh, MS Windows 10 (not activated) PC. For the installetion I picked a different hard disk like:
J:\ProgramFiles\zecwallet

the listing there contains just four files:
LICENSE
README.md
zcash-cli.exe
zecwallet.exe

when I first tried to run the application I got a message by Windows Defender about zcashd which I allowed for both public and private networks.

After that and everytime I try to run the application I get an error about zcashd. I deleted (actually renamed) the params but the problem remains after rebuilding them. Installed, re-installed but nothing.

![error](https://user-images.githubusercontent.com/52919210/61214791-8a6a0f80-a711-11e9-8521-23f04e313dd5.jpg)

**Comment by adityapk00** [comment]
Thanks for reporting this bug. I think the problem is that your computer is missing the zcashd.exe file in the directory. There should be 5 files (you're missing zcashd.exe) in the directory. 

I think your Windows defender/AV or something else is preventing the installation of the zcashd.exe (Which is the embdedded zcashd). 

Can you go to a command prompt and try to see if the file is really gone? If it exists, can you try running zcashd.exe from the command prompt?
