### ISSUE TITLE
rip wallet.dat

### ISSUE THREAD

**Issue by astorsos** [ZcashFoundation/zecwallet#217]
hello.
Yesterday i discovered the problem below
![wallet](https://user-images.githubusercontent.com/60164438/72859575-2b034280-3ce6-11ea-888a-b1210bd2bc2c.jpg)

I tried to replace backup but it didnt help
File wasnt corrupted for sure so i think its kinda bug
lost a lot of money and i hope developer will add salvage function or smth
thanks for attention

**Comment by adityapk00** [comment]
That's unfortunate. If you have backup of the keys (An export of the private keys, you can import them and recover your funds). Otherwise, this is a zcashd error, so you can try filing an issue with zcashd here: https://github.com/zcash/zcash and see if they can recover it.

**Comment by leto** [comment]
@astorsos this is most likely because how ZecWallet was shut down in a "hard" way or some bad edge case happened (CTRL-C or the computer was shut off or ran out of battery or some other edge case), it's not related to a bug in ZecWallet but in hardware or zcashd. Did this happen on Windows? CTRL-C or "killing" a process on Windows can do bad things like this. Always try to shut down the GUI cleanly, especially on Windows.

 Did your hard-drive fill up or do you know of any hard-drive issues? 

You can run `zcashd --salvagewallet` on the CLI and see if that helps. There is currently no GUI option for `-salvagewallet`. If that still doesn't help, I have code which can dump data from corrupt wallet.dat's : https://github.com/leto/wack

Good luck! It could be that lots of private keys are still in your corrupt wallet.dat, but some may be lost. No way to tell if you had funds or not in those without looking at the data.

 You can contact me via Keybase if you like: http://keybase.io/dukeleto
