### ISSUE TITLE
Zecwallet Fullnode wallet isn't syncing on Mac, how do I fix this? 

### ISSUE THREAD

**Issue by chris824** [ZcashFoundation/zecwallet#254]
I spent $600 on ZEC and transferred it from my Kraken account to Zecwallet Fullnode and it has not shown up after an hour. The Fullnode wallet says syncing is still at 0% which i suspect may be the reason. How do I fix this?

**Comment by adityapk00** [comment]
If you have the TxID, you can check it on a block explorer and confirm that it came to you. The reason that you don't see it in your zecwallet is because the blockchain is not synced yet. After the blockchain is synced, you'll be able to see it in your Zecwallet.

You can find more help around how to sync your blockchain more reliably here: https://docs.zecwallet.co/troubleshooting/#my-node-isnt-syncing-or-is-slow-to-sync

Side note: If you are not comfortable with the command line or the zcashd daemon, you should really be using the Lite wallet (www.zecwallet.co). That doesn't require a download and syncs in seconds.
