### ISSUE TITLE
issue connection to mainnet with version 9.15

### ISSUE THREAD

**Issue by alex82361** [ZcashFoundation/zecwallet#282]
After the latest update i am not able to connect to the main-net after about 3 or 4 % sync. I had to revert back to 9.12 which is known good. On a side note i am not sure why i am syncing everytime i am opening zecwallet.

**Comment by adityapk00** [comment]
I think it would be best if you ran zcashd separately, so that you can see what syncing issues you have. When you launch Zecwallet, it will automatically connect to the zcashd that you are running. 

On a side note, I think you should consider using Zecwallet Lite, the light client. It doesn't need to sync, is much faster, and has no dependency on zcashd or downloading the blockchain. www.zecwallet.co

**Comment by adityapk00** [comment]
You can also see this FAQ for syncing issues. https://docs.zecwallet.co/troubleshooting/#my-node-isnt-syncing-or-is-slow-to-sync
