### ISSUE TITLE
[Bug] "Export All Private Keys" does not export change addresses

### ISSUE THREAD

**Issue by skironDotNet** [ZcashFoundation/zecwallet#295]
When you click File -> Export All Private Keys you'll get priv keys only for those who are shown in "Receive" tab, but not for change address

**Comment by adityapk00** [comment]
Are you talking about transparent keys or shielded keys. Note that zcash doesn't use "change addresses" for shielded addresses, since the change is sent back to the same address.

**Comment by skironDotNet** [comment]
I'm talking about transparent, I know how zcash works ;)

**Comment by skironDotNet** [comment]
also it could call dumpwallet to memory location if possible and then output all addresses from parting that dump data? 
I see now some challenges are that Zecwallet GUI has no control like BTC based wallets and needs to talk to zcashd via API. So this may also need to be addressed at zcashd level

**Comment by interbiznw** [comment]
Yes, just found this bug as well. When sending partial funds from a T address the rest of the funds "change" are sent to a new address, that address is not listed on the Receive tab list of addresses and only shown on the Dashboard. So there is no way to export it individually and when run Export all, that address ***WITH FUNDS*** Is not included in an export

**Comment by interbiznw** [comment]
Looks like maybe the reason is that the Imported addresses are getting assigned a label "imported" (rpc.js:238) and therefore when the `taddrsPromise` (rpc.js:422) is called to return all addresses it returns only addresses in " " account which are only the ones created by the gui wallet. as others are  assigned a "label" or different "account"

and in addition to that, the change addresses have no label or account and do not even have the field for it therefore are also not being included in the address list (see below)

![image](https://user-images.githubusercontent.com/16450422/112927838-796e5700-90ca-11eb-95db-740f7fc04bf8.png)

and in the getaddressesbyaccount "" returns neither of the addresses

![image](https://user-images.githubusercontent.com/16450422/112927946-a6bb0500-90ca-11eb-8468-eeb6a31f5b64.png)

**Comment by interbiznw** [comment]
#317 fixes this and was merged. Issue solved

**Comment by interbiznw** [comment]
@adityapk00 feel free to close this as the PR #317 I submitted and you merged fixed this issue
