### ISSUE TITLE
Zcashd 1.8.1 doesn't start on windows 10 and Mac Os

### ISSUE THREAD

**Issue by tanzwu** [ZcashFoundation/zecwallet#372]
I'll leave it as a comment
fullnode client not starting
Same error on both machines
<img width="1195" alt="Снимок экрана 2022-07-19 в 19 42 07" src="https://user-images.githubusercontent.com/109588694/179720347-4ccb177f-ae3d-4263-a3cb-e1927854561d.png">

**Comment by tanzwu** [comment]
I'll leave it as a comment
fullnode client not starting
Same error on both machines
<img width="1195" alt="Снимок экрана 2022-07-19 в 19 42 07" src="https://user-images.githubusercontent.com/109588694/179720347-4ccb177f-ae3d-4263-a3cb-e1927854561d.png">

**Comment by adityapk00** [comment]
Is zcashd running?

**Comment by tanzwu** [comment]
of course
<img width="1979" alt="Снимок экрана 2022-07-20 в 12 13 05" src="https://user-images.githubusercontent.com/109588694/179881272-37f5e2ef-4616-44c4-bf27-f0f66117a2c2.png">

**Comment by tanzwu** [comment]
now after synchronization it shows that I don't have a wallet
<img width="1898" alt="Снимок экрана 2022-07-20 в 18 51 40" src="https://user-images.githubusercontent.com/109588694/179940699-13a5f682-17f0-43f8-92fe-6e125e3ad9e4.png">

**Comment by adityapk00** [comment]
Ok, so now you need to run `zcashd-wallet-tool (included in the distribution). This will let you initialize your wallet and save your seed phrase. 

If you have any private keys, you should import them too and wait for the rescan to finish

**Comment by melkiy84** [comment]
<img width="662" alt="image" src="https://user-images.githubusercontent.com/49388328/180152673-73e1fa14-6e08-4abb-ad70-49d8d4558d21.png">
When I trying to start zcashd with -exportdir param., i recieve this 
<img width="667" alt="image" src="https://user-images.githubusercontent.com/49388328/180152982-f0be0f82-176f-4ec9-b7a8-7da251221c62.png">

**Comment by morein22** [comment]
Indeed, same problems on limux.

**Comment by gades** [comment]
The same issue on MacOS because zcashd is not starting with wallet 

After run it manually you will see following error 
Error: Error invoking remote method 'doRPC_IPC': {"code":-28,"message":"This wallet operation is disabled while reindexing."}

**Comment by aleksey988** [comment]
> I'll leave it as a comment fullnode client not starting Same error on both machines <img alt="Снимок экрана 2022-07-19 в 19 42 07" width="1195" src="https://user-images.githubusercontent.com/109588694/179720347-4ccb177f-ae3d-4263-a3cb-e1927854561d.png">

same problem.you found solution?

**Comment by morein22** [comment]
Yes, i resolved this problem. I install last version wallet and run on command line zcashd. When i dowloaded all blocks i reinstall version of wallet 1.78 and this wallet runned with all my wallets with full balance. My be just installed 1.78 version can used but i didn't check it.
 
Добрый вечер!
Возможно вы понимаете судя по имени на русском. Тогда вкратце опишу как решил. Бился я с новыми обновлениями и сделать ничего нельзя было. Только выкачать блокчейн запустив из коммандной строки zcashd. Кошелек на новой версии запускался, но пустой с предложением запустить zcash-cli и создать новые кошельки… Делать это я не решился и решил дождаться может быть они что-то там решать все же, но потом вычитал, что старая версия работает, но очень медленно.  Т.к. блокчейн был выкачен через коммандную строку на нерабочей новой версии, я просто потом переустановил старую версию и пройдя синхронизацию кошелек с полным балансом и старыми кошельками был запущен… Как-то так…
 
С уважением,
Денис.
  
>Среда, 17 августа 2022, 15:12 +03:00 от aleksey988 ***@***.***>:
> 
> 
>I'll leave it as a comment fullnode client not starting Same error on both machines 
same problem.you found solution?
—
Reply to this email directly,  view it on GitHub , or  unsubscribe .
You are receiving this because you commented. Message ID:  <ZcashFoundation/zecwallet/issues/372/1217927528 @ github . com>  
 
--
Денис Филиппов

**Comment by aleksey988** [comment]
> Yes, i resolved this problem. I install last version wallet and run on command line zcashd. When i dowloaded all blocks i reinstall version of wallet 1.78 and this wallet runned with all my wallets with full balance. My be just installed 1.78 version can used but i didn't check it.   Добрый вечер! Возможно вы понимаете судя по имени на русском. Тогда вкратце опишу как решил. Бился я с новыми обновлениями и сделать ничего нельзя было. Только выкачать блокчейн запустив из коммандной строки zcashd. Кошелек на новой версии запускался, но пустой с предложением запустить zcash-cli и создать новые кошельки… Делать это я не решился и решил дождаться может быть они что-то там решать все же, но потом вычитал, что старая версия работает, но очень медленно.  Т.к. блокчейн был выкачен через коммандную строку на нерабочей новой версии, я просто потом переустановил старую версию и пройдя синхронизацию кошелек с полным балансом и старыми кошельками был запущен… Как-то так…   С уважением, Денис.  
> Среда, 17 августа 2022, 15:12 +03:00 от aleksey988 ***@***.***>:     I'll leave it as a comment fullnode client not starting Same error on both machines
> same problem.you found solution? — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you commented. Message ID: <ZcashFoundation/zecwallet/issues/372/1217927528 @ github . com>     -- Денис Филиппов

![z](https://user-images.githubusercontent.com/106724946/185308947-d9961634-e417-4074-bdb7-0702395140ad.png)
its working.спасибо большое работает отправил небольшую суму на zecwallet lite деньги пришли

**Comment by tanzwu** [comment]
Сделал аналогично, но всё же ветку закрывать не буду пока разработчики не вернут/завершат нормальное приложение без танцев с бубнами и командной строкой. Мне то понятно, есть пользователи, которым не объяснишь что нужно сейчас запускать именно таким образом
